### ISSUE TITLE
Key explanation of what this does, seems confusing. +additional comments

### ISSUE THREAD

**Issue by bdklahn** [davidbartonau/zbackup-tar#10]
This looks very interesting, and I might try it. But . . .
In README.md, "zbackup-tar is a very relaxed incremental tarring tool. Very relaxed means that the cost of tarring a file we don't need is very low (since it will be deduplicated) so we can tar files we don't strictly need." seems confusing, Looking at the code, it seems like this tool maintains a flat file "database" of timestamps, so it can avoid tarring unmodified files AT ALL. -not that it lowers the cost of tarring. It DOESN'T appear to ". . . tar files we don't strictly need." I don't know if I am wrong about how this works. Either way, I don't know if it might make people try this (and maybe contribute), rather than move on to find other software, if it were clearer at the beginning what this tool does for you. It almost seems this could be a module directly contributed to the zbackup project itself. It seems like the addition of this functionality could make zbackup an ideal backup solution (rather than, basically, a stream compressor, with a cloud-friendly bundle generation process). Another thought: zbackup has that "tartool", which basically helps with  creating ignore-this-file/dir-type files in the directory tree. Couldn't a script like this, work with that? -a preprocessor, rather than a front-end for zbackup? Maybe I missed something, and it does. Anyway, it looks like this project might have been abandoned, as I see no commits for a year.

**Comment by davidbartonau** [comment]
Hi bdklahn,

Sorry for the delay in responding, I missed the notification about your comment.

I do hope to get this incorporated into zbackup one day, but that is a C++ project and this is unproven so I wanted to see if there was any support for it.  Up to this year, there has not been any interest.

zbackup-tar is under development, although I'm sorry to say I don't make my commits to Github but just in my local Puppet repository.  

I am backing up about 500GB of data across ~100 servers using this tool.  For me it is absolutely critical it works as zbackup is unsuitable in its raw state.

Hope you'll give the tool another look.  I love zbackup and I think this is a good addition to what it does.

Perhaps the description could be better worded, if you have a suggestion for iprovement I'd be happy to consider it.
David
