### ISSUE TITLE
Test fails on "diff --no-dereference" 

### ISSUE THREAD

**Issue by pol** [davidbartonau/zbackup-tar#12]
Running the tests fail with the following message:

```
diff: unrecognized option '--no-dereference'
diff: Try `diff --help' for more information.
[UNIT TEST] FAIL Restoring backup01.tar
```

Perhaps I am using an older version of diff than is expected?  The version that I have is: 

```
[root@hyalite tests]# diff --version
diff (GNU diffutils) 2.8.1
```

**Comment by davidbartonau** [comment]
I am using diff (GNU diffutils) 3.3, so your one seems much older.

Doing a normal diff against a directory with a broken link causes diff to fail unless --no-dereference is passed.  The flag is not well documented.  Unfortunately test16 is supposed to ensure that it can restore tars that have broken links (used to fail in an earlier version).  

Are you able to comment out test.sh:417 and then remove all --no-dereference where diff is used in test.sh and test_Functions.sh?  If not, I can try to commit a patch in a few days for you to try.

BTW, this won't stop zbackup-tar from working, it just means the test suite is broken.

**Comment by pol** [comment]
Understood, I just wanted a better idea of what the zbackup archive looked like after using zbackup-tar. So the tests seemed a good place to start. I will see if I can get around the diff issue and report back.

**Comment by davidbartonau** [comment]
Let me know how you go.  

The doco has a bit on this, but I realised that the README still refers to the old XML manifests, whereas manifests are now CSVs for memory usage.  It looks like the doco needs a bit of an update as the file includes / excludes parameters are also omitted.

**Comment by davidbartonau** [comment]
Can you checkout  hotfix/Hotfix-DiffBrokenSimlinks.  If you:
`export  DIFF_NO_DEREFERENCE=1`
before running test.sh it will not create the broken link and won't use the special mode of diff.
