### ISSUE TITLE
mising file error

### ISSUE THREAD

**Issue by sfarrell5123** [davidbartonau/zbackup-tar#13]
when making initial backup, a file must have been deleted after the initial scan, and the backup crashed

Traceback (most recent call last):
  File "./zbackup-tar", line 932, in <module>
    main()
  File "./zbackup-tar", line 896, in main
    retCode = handleBackupCreation(cParser.parse_args())
  File "./zbackup-tar", line 634, in handleBackupCreation
    createZBackup(nBackup, pArgs.aFlags)                                
  File "./zbackup-tar", line 421, in createZBackup
    tar.add (name = fullFile, arcname = nameInTar, recursive = False)
  File "/usr/lib64/python3.4/tarfile.py", line 1907, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib64/python3.4/tarfile.py", line 1779, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory:

**Comment by davidbartonau** [comment]
Thanks for reporting this.  I'll look into it.

The FileNotFoundError seems non-fatal, so I'll just continue processing the next file and remove the missing file from the manifest.

**Comment by davidbartonau** [comment]
I just tested and pushed a fix.  I created a 1G repository which takes long enough to backup that I was able to delete files while it was in the process.  There is logging to say it's happened and I checked the manifest to be sure the files were removed.

**Comment by sfarrell5123** [comment]
Thanks

Scott Farrell
