### ISSUE TITLE
manifest file error

### ISSUE THREAD

**Issue by sfarrell5123** [davidbartonau/zbackup-tar#14]
I did an original backup, and that worked well, thanks for your disappearing file patch - that seemed to let the backup complete

the manifest file is 80 bytes - does that sound correct

when I run the next backup I get an error - almost straight away (I git cloned earlier today)

  File "/usr/bin/zbackup-tar", line 938, in <module>
    main()
  File "/usr/bin/zbackup-tar", line 902, in main
    retCode = handleBackupCreation(cParser.parse_args())
  File "/usr/bin/zbackup-tar", line 625, in handleBackupCreation
    mDict = readCSVManifestFC(pArgs.pBackup+'.manifest', pArgs.aFlags)
  File "/usr/bin/zbackup-tar", line 163, in readCSVManifestFC
    for row in csvReader:  
_csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

**Comment by davidbartonau** [comment]
It looks like the .csv file is corrupt.  I don't see how that could happen.  The CSV is written using the CSV module, so it should escape wherever is needed.  Do you have any odd filenames that you are backing up?

The manifest file is not 80 bytes, the file is just a handle into the zbackup repository.

If you run the following, it should give you the full CSV, where mybackup.manifest is the full path to the manifest.
zbackup restore ----non-encrypted mybackup.manifest | less

The error may be obvious.  Is there anything private that stops you from posting a copy here?

The file is actually a converted byte stream sent via stdout from zbackup, so the opportunity to specify universal newlines is not obvious.

**Comment by sfarrell5123** [comment]
I grepped the csv, each line ended in 0$ or 1$ according to grep

looking at your csv - you definately need to escape the filename field

here is the filename of a stored email  - notice the comma in the file name

./mail/
xxx.com/andrew/cur/1443567448.H177416P30576.id.vp.pre.net.au,S=216448:2,S

I am sure it will trip up on many other characters if not escaped more
accurately.

perhaps use some function to base64 encode, or uuencode,

**Comment by davidbartonau** [comment]
That looks like an IMAP mail store.  I back up exactly the same thing:

# zbackup restore --silent --non-encrypted backups/zbackup/backups/2016-05/04/09_23/var_mail_vhosts_1it.com.au_dave.tar.manifest | head

HEADER,1,1394
./.Archive,4096,1447037342,1462088521,backups/2016-05/01/15_23/var_mail_vhosts_1it.com.au_dave.tar,5000,5000,0
./.Archive 13,4096,1462306528,1462315346,backups/2016-05/04/06_23/var_mail_vhosts_1it.com.au_dave.tar,5000,5000,0
./.Archive 13.2013-01 Analyst,4096,1447800917,1462077708,backups/2016-05/01/12_23/var_mail_vhosts_1it.com.au_dave.tar,5000,5000,0
./.Archive 13.2013-01 Analyst/cur,12288,1447247984,1462131690,backups/2016-05/02/03_23/var_mail_vhosts_1it.com.au_dave.tar,5000,5000,0
"./.Archive 13.2013-01 Analyst/cur/1359353024.M998515P3692.DovecotProd2,S=128647,W=130350:2,S",128647,1359353025,1462164248,backups/2016-05/02/12_23/var_mail_vhosts_1it.com.au_dave.tar,5000,5000,1
"./.Archive 13.2013-01 Analyst/cur/1359355547.M730284P4160.DovecotProd2,S=129912,W=131708:2,Sa",129912,1359355547,1462142483,backups/2016-05/02/06_23/var_mail_vhosts_1it.com.au_dave.tar,5000,5000,1


Notice how the last few lines use quotes and they have the , in the filename.  

What version of python are you running and what OS?

**Comment by davidbartonau** [comment]
You also need to run python3, otherwise you'll probably get a python2 interpreter.

FYI I am using 3.2.3 on Ubuntu 12.04. I have tested it on 14.04 and 16.04 as well.

I guess I have the option of forcing quotes on every field, which I was hoping to avoid for space sake.

**Comment by sfarrell5123** [comment]
here's my manifest entry
I have no escaping at all in my manifest

.cpan/build/Class-Accessor-0.34-2dbCEZ/MANIFEST,258,1252767749,1465148127,backups/init.tar,1000,1000,1

**Comment by sfarrell5123** [comment]
OH ok - you selectively escape the filenames with commas

can I send you my manifest file to check , it must be a character you are missing. I can send you a http url to download a compressed manifest file

I dont think storing extra quote characters makes much difference to size, is the manifest compressed - if so it's likely a minimal difference.

**Comment by davidbartonau** [comment]
If you send me the manifest URL I will have a look.

Also which python3 are you using? (/usr/bin/python3 --version)

It worries me that I have the CSV to escape where required and I might change it to always and it still won't work for you.  Alternatively, do you want to try editing line 241:
csvWriter = csv.writer(sIO, dialect = 'unix', quoting = csv.QUOTE_MINIMAL)
and change it to:
csvWriter = csv.writer(sIO, dialect = 'unix', quoting = csv.QUOTE_NONNUMERIC)

If that fixes your problem then I will commit the change.  

FYI I have been backing up ~100 different mailboxes (each in a separate backup to make restoration easier) for about 9 months with good results.  I have noticed that the repository starts to bloat after a while.  Using zbackup 1.4.4 with the gc option alleviates the problem to an extent but I am hoping 1.5 with its index aggregation will make a major difference to backup / restore times.

**Comment by sfarrell5123** [comment]
it did seem to let the 2nd backup complete OK (changing to the code to QUOTE_NONNUMERIC)

**Comment by davidbartonau** [comment]
Fantastic, I'll commit that as a change when I get to work.  Thanks for identifying and helping me resolve this.

**Comment by davidbartonau** [comment]
Funnily enough while testing this change I just noticed that names with " and ' are part of the test suite.  I have tested and this change is backwards compatible.
